---
- name: Backup Huawei S5735 via CLI Command
  hosts: 192.168.100.15
  gather_facts: no
  connection: network_cli
  ansible_network_os: huawei.network.vrp
  vars:
    ftp_server: "192.168.100.64"
    ftp_user: "ftpuser"
    ftp_pass: "ftpuser"
    backup_dir: "./backups"

  tasks:
    - name: Create local backup directory
      file:
        path: "{{ backup_dir }}"
        state: directory
      delegate_to: localhost

    - name: Run display current-configuration on switch
      ansible.netcommon.cli_command:
        command: display current-configuration
      register: config_output

    - name: Save configuration to local file
      copy:
        content: "{{ config_output.stdout }}"
        dest: "{{ backup_dir }}/{{ inventory_hostname }}_config.cfg"
      delegate_to: localhost

    - name: Upload to FTP Server
      delegate_to: localhost
      ansible.netcommon.net_put:
        src: "{{ backup_dir }}/{{ inventory_hostname }}_config.cfg"
        dest: "/network_backups/{{ inventory_hostname }}.cfg"
        protocol: ftp
      vars:
        ansible_user: "{{ ftp_user }}"
        ansible_password: "{{ ftp_pass }}"
        ansible_host: "{{ ftp_server }}"