---
- name: Backup Huawei S5735 Configuration and Upload to FTP
  hosts: huawei_switches192.168.100.15
  gather_facts: no
  vars:
    # Sesuaikan dengan detail server FTP Anda
    ftp_server: "192.168.100.64"
    ftp_user: "ftpuser"
    ftp_pass: "ftpuser"
    backup_dir: "./backups"

  tasks:
    - name: Create local backup directory
      file:
        path: "{{ backup_dir }}"
        state: directory
      delegate_to: localhost

    - name: Get running configuration from Huawei Switch
      community.network.ce_config:
        backup: yes
        backup_options:
          filename: "{{ inventory_hostname }}_config.cfg"
          dir_path: "{{ backup_dir }}"
      register: backup_result

    - name: Upload configuration to FTP Server
      delegate_to: localhost
      ansible.netcommon.net_put:
        src: "{{ backup_dir }}/{{ inventory_hostname }}_config.cfg"
        dest: "/network_backups/{{ inventory_hostname }}_{{ ansible_date_time.date }}.cfg"
        protocol: ftp
        remote_to_local: no
      vars:
        ansible_user: "{{ ftp_user }}"
        ansible_password: "{{ ftp_pass }}"
        ansible_host: "{{ ftp_server }}"

    - name: Confirm Backup Status
      debug:
        msg: "Konfigurasi {{ inventory_hostname }} telah berhasil di-backup dan dikirim ke FTP."